name: SLclaim
version: 1.12.3.3
main: fr.mrbaguette07.SLclaim.SLclaim
authors: [MrBaguette07]
softdepend: [PlaceholderAPI, WorldGuard, Vault, BlueMap, floodgate, ItemsAdder]
api-version: 1.18
folia-supported: true
commands:
  claim:
    description: Commande de base pour les claims
    aliases: []
    permission: slclaim.command.claim
  claims:
    description: Tous les claims
    aliases: []
    permission: slclaim.command.claims
  unclaim:
    description: Supprimer votre territoire
    aliases: []
    permission: slclaim.command.unclaim
    default: true
  slclaim:
    description: Commandes administrateur
    aliases: [scs]
    permission: slclaim.admin
  protectedarea:
    aliases: [parea,pa]
    description: Commandes des zones protégées
    permission: slclaim.admin
  rtp:
    aliases: [randomtp, randomteleport]
    description: Téléportation aléatoire
    permission: slclaim.rtp.use
    
permissions:
  slclaim.command.claim:
    description: Commande de base pour les claims
    default: true
  slclaim.command.claim.*:
    description: Commande de base pour les claims
    default: true
  slclaim.command.unclaim:
    description: Supprimer votre territoire
    default: true
  slclaim.admin:
    description: Commandes administrateur
    default: op
  slclaim.command.claims:
    description: Interface des claims
    default: true
  slclaim.setting.*:
    description: Permissions des paramètres
    default: true
  slclaim.rtp.use:
    description: Permet d'utiliser /rtp
    default: true
  slclaim.rtp.bypass:
    description: Bypass le délai de téléportation RTP
    default: op
  slclaim.rtp.nocooldown:
    description: Pas de cooldown pour RTP
    default: op
  slclaim.rtp.vip:
    description: Délai réduit pour VIP
    default: false
  slclaim.rtp.mvp:
    description: Délai réduit pour MVP
    default: false
  slclaim.rtp.elite:
    description: Délai réduit pour Elite
    default: false
  slclaim.rtp.staff:
    description: Aucun délai pour Staff
    default: op